// This page is used as the / routes (home page tbh)

import Head from "next/head";
// import Image from 'next/image'

// importing style sheet from styles here
import styles from "@/styles/index.module.css"; 

export default function Home() {
  return (
    <>
      <Head>
        <title>My First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* This is how you apply style in the element styles._name_ */}
      <main className={styles.main}>
        <h1>My First Next App</h1>
        
      </main>
    </>
  );
}
